export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const DESTROY_SESSION = 'DESTROY_SESSION';

// Passenger Types Declarations
export const LOAD_PASSENGERS_SUCCESS = 'LOAD_PASSENGERS_SUCCESS';
export const CREATE_PASSENGER_SUCCESS = 'CREATE_PASSENGER_SUCCESS';
export const UPDATE_PASSENGER_SUCCESS = 'UPDATE_PASSENGER_SUCCESS';
export const DELETE_PASSENGER_OPTIMISTIC = 'DELETE_PASSENGER_OPTIMISTIC';

// Ancillary Types Declarations
export const LOAD_ANCILLARY_SUCCESS = 'LOAD_ANCILLARY_SUCCESS';
export const CREATE_ANCILLARY_SUCCESS = 'CREATE_ANCILLARY_SUCCESS';
export const UPDATE_ANCILLARY_SUCCESS = 'UPDATE_ANCILLARY_SUCCESS';
export const DELETE_ANCILLARY_OPTIMISTIC = 'DELETE_ANCILLARY_OPTIMISTIC';

// Check in Passenger Details
export const CREATE_CHECKIN_PASSENGER_SUCCESS = 'CREATE_CHECKIN_PASSENGER_SUCCESS';
export const UPDATE_CHECKIN_PASSENGER_SUCCESS = 'UPDATE_CHECKIN_PASSENGER_SUCCESS';
export const LOAD_CHECKIN_PASSENGERS_SUCCESS = 'LOAD_CHECKIN_PASSENGERS_SUCCESS';
export const DELETE_CHECKIN_PASSENGER_OPTIMISTIC = 'DELETE_CHECKIN_PASSENGER_OPTIMISTIC';
